### ISSUE TITLE
Unable to make a Withdraw

### ISSUE THREAD

**Issue by carsonholoien** [craysiii/binance#18]
Thanks so much for putting together this gem, it's made accessing Binance's API so much easier when using Ruby.  

I'm currently having an issue, when executing the `withdraw` endpoint.  I continue to receive this error: 

`{"msg"=>"The operation failed, please try again later.", "success"=>false}`

I have already, added withdraw permissions to my api keys, but still receive this.  Has anyone seen this before?

**Comment by craysiii** [comment]
Hey there!

Can you paste the line of code you’re calling?

I will mess with it in a bit. Haven’t actually made to many withdrawals myself.

**Comment by carsonholoien** [comment]
Hey!
I ended up finding my issue.  I was passing a an entire symbol instead of the exact amount.  As in: `amount = amount=>0.002` instead of amount=0.002.  

After changing it everything works great! Thanks again for putting together this gem!

**Comment by craysiii** [comment]
Awesome! Thanks!
