### ISSUE TITLE
new mandatory parameters "timeInForce" for certain trade types

### ISSUE THREAD

**Issue by yawhide** [craysiii/binance#24]
Hello,

Binance now requires timeInForm for certain trade types.
Here is their chart:

Type | Additional mandatory parameters
-- | --
LIMIT | timeInForce, quantity, price
MARKET | quantity
STOP_LOSS | quantity, stopPrice
STOP_LOSS_LIMIT | timeInForce, quantity, price, stopPrice
TAKE_PROFIT | quantity, stopPrice
TAKE_PROFIT_LIMIT | timeInForce, quantity, price, stopPrice
LIMIT_MAKER | quantity, price

```
[9] pry(#<Index>)> client.create_test_order(symbol: "ETHBTC", side: "BUY", type: "LIMIT", quantity: "1.00000000")
=> {"code"=>-1102, "msg"=>"Mandatory parameter 'timeInForce' was not sent, was empty/null, or malformed."}
```

**Comment by craysiii** [comment]
Hey there, sorry for the late response.

We don't actually validate parameters passed to methods, so you should be able to pass a time_in_force parameter and it should work. Let me know if it doesn't.

**Comment by yawhide** [comment]
for some reason I thought timeInForce was a timestamp thing that you auto generate for me. sorry for bothering

**Comment by craysiii** [comment]
No worries :)
