### ISSUE TITLE
My Trades Data Fetch Issue

### ISSUE THREAD

**Issue by mchalise** [craysiii/binance#28]
I have done like 1900 trades with ETHUSD pair. This endpoint is only giving me like 1000 transaction 
`client.my_trades(symbol: 'ETHUSDT')`
Is there any way to fetch all my transactions. Thanks

**Comment by craysiii** [comment]
You have to provide a from_id in the query in order to see older trades. 1000 is the max amount of trades that the API will return in a single call. You can read more here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#account-trade-list-user_data

**Comment by mchalise** [comment]
Already did but **from_id** only return up to 1000th record. eg. if I provide 600th id then it will return data from 600th id to 1000th id not more than that. I think I need to play with start-end time. I don't know.

**Comment by mchalise** [comment]
@craysiii  Just got reply from support team

> Hello,
> 
> Thanks for your inquiry.
> 
> About your question, currently, for the GET /api/v3/myTrades (HMAC SHA256) interface, the limit is maxed 1000. 
> 
> Temporarily uneditable, you can use start time and end time to set the period and query your trade history separately.
> 
> Thank you for your understanding.
> 
> Best Regards,
> Binance Support Team

Help needed man. Support team is not help full at all.

**Comment by mchalise** [comment]
The little hack did the magic. got the data.
