### ISSUE TITLE
product endpoint?

### ISSUE THREAD

**Issue by gsdean** [craysiii/binance#3]
Im curious, where did you find out about the `product` endpoint

https://github.com/craysiii/binance/blob/master/lib/binance/client/rest/public_api.rb#L32

**Comment by craysiii** [comment]
Hey @gsdean, I initially heard of the product endpoint while reading through the Binance API Telegram chat. I also found a reference to it in the python-binance API wrapper, so figured I should include it in ours.

**Comment by gsdean** [comment]
Oh cool, it's not officially documented anywhere I could find. I'm looking over the gem now, looks great, thanks for the hard work!

**Comment by craysiii** [comment]
Yeah the endpoint isn't part of the official API. I hope they decide to document it.

Also, thanks! I want to have basic WebSocket support done by the end of the week. Been a busy week.
