### ISSUE TITLE
LOST type and Dust to BNB

### ISSUE THREAD

**Issue by mchalise** [craysiii/binance#30]
Hi,
Is there any way to fetch Dust to BNB trades and the LOST type transaction?

**Comment by craysiii** [comment]
I have to update the gem. I’ve been really busy with work and have neglected this unfortunately, but hopefully I will get to it soon. If that is in the new API, then it should be feasible. Sorry about that

**Comment by mchalise** [comment]
`dust_log:  'v3/userAssetDribbletLog.html' `  
Ok its already there.
